CREATE TABLE public.profiles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname    VARCHAR(255),
    phone       VARCHAR(255),
    img         VARCHAR(255),
    verified    BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_profiles_account FOREIGN KEY (id) REFERENCES accounts(id)
);